[
  {
    "roomNumber": 101,
    "seat": "A",
    "name": "Samiul Hasan",
    "department": "CSE",
    "studentId": "CSE101",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Nurul Hasan",
    "motherName": "Hasina Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 600000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Samiul_Hasan_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 101,
    "seat": "B",
    "name": "Mohiuddin Rahman",
    "department": "BBA",
    "studentId": "BBA101",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdur Rahman",
    "motherName": "Nasrin Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Mohiuddin_Rahman_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 101,
    "seat": "C",
    "name": "Ahsan Habib",
    "department": "EEE",
    "studentId": "EEE101",
    "season": "2021-22",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Karim",
    "motherName": "Amina Karim",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Teacher",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "018XXXXXXXX",
    "signature": "Ahsan_Habib_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 101,
    "seat": "D",
    "name": "Ruhul Amin",
    "department": "ME",
    "studentId": "ME101",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Kamal Uddin",
    "motherName": "Rokeya Begum",
    "fatherOccupation": "Lecturer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 800000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Ruhul_Amin_Signature.png",
    "timeRemaining": "5 months"
  },
  {
    "roomNumber": 102,
    "seat": "A",
    "name": "Rabiul Alam",
    "department": "CSE",
    "studentId": "CSE102",
    "season": "2023-24",
    "yearOrSemester": "1st Year",
    "fatherName": "Shamsul Alam",
    "motherName": "Momena Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 450000,
    "mobileNumber": "016XXXXXXXX",
    "signature": "Rabiul_Alam_Signature.png",
    "timeRemaining": "11 months"
  },
  {
    "roomNumber": 102,
    "seat": "B",
    "name": "Nazmul Hossain",
    "department": "BBA",
    "studentId": "BBA102",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdullah Al Mamun",
    "motherName": "Rina Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 550000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Nazmul_Hossain_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 102,
    "seat": "C",
    "name": "Jamil Hossain",
    "department": "EEE",
    "studentId": "EEE102",
    "season": "2021-22",
    "yearOrSemester": "3rd Year",
    "fatherName": "Ismail Hossain",
    "motherName": "Feroza Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 600000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Jamil_Hossain_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 102,
    "seat": "D",
    "name": "Mehedi Hasan",
    "department": "ME",
    "studentId": "ME102",
    "season": "2023-24",
    "yearOrSemester": "1st Year",
    "fatherName": "Moynul Hasan",
    "motherName": "Nargis Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 350000,
    "mobileNumber": "016XXXXXXXX",
    "signature": "Mehedi_Hasan_Signature.png",
    "timeRemaining": "14 months"
  },
  {
    "roomNumber": 103,
    "seat": "A",
    "name": "Shihab Uddin",
    "department": "CSE",
    "studentId": "CSE103",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Shah Alam",
    "motherName": "Sabina Yasmin",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Shihab_Uddin_Signature.png",
    "timeRemaining": "4 months"
  },
  {
    "roomNumber": 103,
    "seat": "B",
    "name": "Tareq Islam",
    "department": "BBA",
    "studentId": "BBA103",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Kamrul Islam",
    "motherName": "Shirin Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tareq_Islam_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 103,
    "seat": "C",
    "name": "Fahim Hossain",
    "department": "EEE",
    "studentId": "EEE103",
    "season": "2021-22",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Hai",
    "motherName": "Momena Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 550000,
    "mobileNumber": "018XXXXXXXX",
    "signature": "Fahim_Hossain_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 103,
    "seat": "D",
    "name": "Asif Alam",
    "department": "ME",
    "studentId": "ME103",
    "season": "2023-24",
    "yearOrSemester": "1st Year",
    "fatherName": "Md. Alamgir",
    "motherName": "Nasrin Akhter",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 400000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Asif_Alam_Signature.png",
    "timeRemaining": "13 months"
  },
  {
    "roomNumber": 104,
    "seat": "A",
    "name": "Samiul Hasan",
    "department": "CSE",
    "studentId": "CSE104",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Nurul Hasan",
    "motherName": "Hasina Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 600000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Samiul_Hasan_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 104,
    "seat": "B",
    "name": "Mohiuddin Rahman",
    "department": "BBA",
    "studentId": "BBA104",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdur Rahman",
    "motherName": "Nasrin Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Mohiuddin_Rahman_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 104,
    "seat": "C",
    "name": "Ahsan Habib",
    "department": "EEE",
    "studentId": "EEE104",
    "season": "2021-22",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Karim",
    "motherName": "Amina Karim",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Teacher",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "018XXXXXXXX",
    "signature": "Ahsan_Habib_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 104,
    "seat": "D",
    "name": "Ruhul Amin",
    "department": "ME",
    "studentId": "ME104",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Kamal Uddin",
    "motherName": "Rokeya Begum",
    "fatherOccupation": "Lecturer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 800000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Ruhul_Amin_Signature.png",
    "timeRemaining": "5 months"
  },
  {
    "roomNumber": 105,
    "seat": "A",
    "name": "Shihab Uddin",
    "department": "CSE",
    "studentId": "CSE105",
    "season": "2023-24",
    "yearOrSemester": "Final Year",
    "fatherName": "Shah Alam",
    "motherName": "Sabina Yasmin",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Shihab_Uddin_Signature.png",
    "timeRemaining": "4 months"
  },
  {
    "roomNumber": 105,
    "seat": "B",
    "name": "Tareq Islam",
    "department": "BBA",
    "studentId": "BBA105",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Kamrul Islam",
    "motherName": "Shirin Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tareq_Islam_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 105,
    "seat": "C",
    "name": "Fahim Hossain",
    "department": "EEE",
    "studentId": "EEE105",
    "season": "2021-22",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Hai",
    "motherName": "Momena Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 550000,
    "mobileNumber": "018XXXXXXXX",
    "signature": "Fahim_Hossain_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 105,
    "seat": "D",
    "name": "Asif Alam",
    "department": "ME",
    "studentId": "ME105",
    "season": "2023-24",
    "yearOrSemester": "1st Year",
    "fatherName": "Md. Alamgir",
    "motherName": "Nasrin Akhter",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 400000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Asif_Alam_Signature.png",
    "timeRemaining": "13 months"
  },
  {
    "roomNumber": 201,
    "seat": "A",
    "name": "Sara Ahmed",
    "department": "CSE",
    "studentId": "CSE201",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Md. Jasim Uddin",
    "motherName": "Shamima Akter",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Sara_Ahmed_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 202,
    "seat": "B",
    "name": "Rohit Khan",
    "department": "EEE",
    "studentId": "EEE202",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Azizur Rahman",
    "motherName": "Nargis Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Teacher",
    "relativeToTangail": "No",
    "annualIncome": 850000,
    "mobileNumber": "018XXXXXXXX",
    "signature": "Rohit_Khan_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 203,
    "seat": "C",
    "name": "Muna Islam",
    "department": "BBA",
    "studentId": "BBA203",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Rafiqul Islam",
    "motherName": "Selina Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "016XXXXXXXX",
    "signature": "Muna_Islam_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 204,
    "seat": "D",
    "name": "Shuvo Das",
    "department": "EEE",
    "studentId": "EEE204",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Mahbubur Rahman",
    "motherName": "Khatun Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 950000,
    "mobileNumber": "019XXXXXXXX",
    "signature": "Shuvo_Das_Signature.png",
    "timeRemaining": "14 months"
  },
  {
    "roomNumber": 205,
    "seat": "A",
    "name": "Nashit Chowdhury",
    "department": "CSE",
    "studentId": "CSE205",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Shamsul Haque",
    "motherName": "Nasrin Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 800000,
    "mobileNumber": "017XXXXXXXX",
    "signature": "Nashit_Chowdhury_Signature.png",
    "timeRemaining": "9 months"
  },

  {
    "roomNumber": 301,
    "seat": "A",
    "name": "Raihan Ahmed",
    "department": "CSE",
    "studentId": "CSE301A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Karim",
    "motherName": "Jahanara Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Raihan_Ahmed_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 301,
    "seat": "B",
    "name": "Samia Sultana",
    "department": "BBA",
    "studentId": "BBA301B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Mohammad Sulaiman",
    "motherName": "Zara Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 800000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Samia_Sultana_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 301,
    "seat": "C",
    "name": "Alamgir Hossain",
    "department": "EEE",
    "studentId": "EEE301C",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Shamsul Alam",
    "motherName": "Rokeya Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Alamgir_Hossain_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 301,
    "seat": "D",
    "name": "Nusrat Jahan",
    "department": "Law",
    "studentId": "LAW301D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Ismail Hossain",
    "motherName": "Shama Akter",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 400000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Nusrat_Jahan_Signature.png",
    "timeRemaining": "14 months"
  },
  {
    "roomNumber": 302,
    "seat": "A",
    "name": "Imran Khan",
    "department": "BBA",
    "studentId": "BBA302A",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Mohammad Khan",
    "motherName": "Mina Khan",
    "fatherOccupation": "Police Officer",
    "motherOccupation": "Teacher",
    "relativeToTangail": "No",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Imran_Khan_Signature.png",
    "timeRemaining": "18 months"
  },
  {
    "roomNumber": 302,
    "seat": "B",
    "name": "Sharmin Akter",
    "department": "CSE",
    "studentId": "CSE302B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Foysal Ahmed",
    "motherName": "Sumaiya Begum",
    "fatherOccupation": "Software Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 950000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Sharmin_Akter_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 302,
    "seat": "C",
    "name": "Rasel Uddin",
    "department": "EEE",
    "studentId": "EEE302C",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Abdul Quader",
    "motherName": "Khatun Begum",
    "fatherOccupation": "Mechanic",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 350000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rasel_Uddin_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 302,
    "seat": "D",
    "name": "Madhurima Saha",
    "department": "Pharmacy",
    "studentId": "PHARM302D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Niranjan Saha",
    "motherName": "Pratima Saha",
    "fatherOccupation": "Shop Owner",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 400000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Madhurima_Saha_Signature.png",
    "timeRemaining": "5 months"
  },
  {
    "roomNumber": 303,
    "seat": "A",
    "name": "Shamim Ahmed",
    "department": "CSE",
    "studentId": "CSE303A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Sayed Ahmed",
    "motherName": "Farida Ahmed",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 450000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Shamim_Ahmed_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 303,
    "seat": "B",
    "name": "Jannatul Ferdous",
    "department": "BBA",
    "studentId": "BBA303B",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Kamal Uddin",
    "motherName": "Rina Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Jannatul_Ferdous_Signature.png",
    "timeRemaining": "14 months"
  },
  {
    "roomNumber": 303,
    "seat": "C",
    "name": "Sifat Hossain",
    "department": "EEE",
    "studentId": "EEE303C",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdul Wahid",
    "motherName": "Shirin Akter",
    "fatherOccupation": "Mechanic",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Sifat_Hossain_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 303,
    "seat": "D",
    "name": "Tariq Aziz",
    "department": "Pharmacy",
    "studentId": "PHARM303D",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Hossain Ali",
    "motherName": "Sufia Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 350000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tariq_Aziz_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 304,
    "seat": "A",
    "name": "Fahim Reza",
    "department": "CSE",
    "studentId": "CSE304A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Sujon Reza",
    "motherName": "Rina Reza",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 750000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Fahim_Reza_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 304,
    "seat": "B",
    "name": "Aminul Islam",
    "department": "BBA",
    "studentId": "BBA304B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdul Kader",
    "motherName": "Aminara Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Aminul_Islam_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 304,
    "seat": "C",
    "name": "Khaled Bin Shafique",
    "department": "EEE",
    "studentId": "EEE304C",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Rafiq Bin Shafique",
    "motherName": "Shahinur Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Khaled_Bin_Shafique_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 304,
    "seat": "D",
    "name": "Shahinul Islam",
    "department": "Law",
    "studentId": "LAW304D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Mohammad Islam",
    "motherName": "Mariam Begum",
    "fatherOccupation": "Government Employee",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 650000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Shahinul_Islam_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 305,
    "seat": "A",
    "name": "Nadim Ahmed",
    "department": "CSE",
    "studentId": "CSE305A",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Abu Hena",
    "motherName": "Shireen Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 450000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Nadim_Ahmed_Signature.png",
    "timeRemaining": "11 months"
  },
  {
    "roomNumber": 305,
    "seat": "B",
    "name": "Shakil Alam",
    "department": "EEE",
    "studentId": "EEE305B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Fahad Alam",
    "motherName": "Nasima Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 900000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Shakil_Alam_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 305,
    "seat": "C",
    "name": "Alim Uddin",
    "department": "BBA",
    "studentId": "BBA305C",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Jabir Uddin",
    "motherName": "Rokeya Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Alim_Uddin_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 305,
    "seat": "D",
    "name": "Nashit Hossain",
    "department": "CSE",
    "studentId": "CSE305D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Mahbub Hossain",
    "motherName": "Afia Begum",
    "fatherOccupation": "Doctor",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1200000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Nashit_Hossain_Signature.png",
    "timeRemaining": "7 months"
  },

  {
    "roomNumber": 401,
    "seat": "A",
    "name": "Rashed Khan",
    "department": "CSE",
    "studentId": "CSE401A",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Mohammad Khan",
    "motherName": "Fariha Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 850000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rashed_Khan_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 401,
    "seat": "B",
    "name": "Sohail Hossain",
    "department": "BBA",
    "studentId": "BBA401B",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Abdul Hossain",
    "motherName": "Shamim Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 400000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Sohail_Hossain_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 401,
    "seat": "C",
    "name": "Zahidul Islam",
    "department": "EEE",
    "studentId": "EEE401C",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Salim Uddin",
    "motherName": "Laily Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 900000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Zahidul_Islam_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 401,
    "seat": "D",
    "name": "Faisal Ahmad",
    "department": "CSE",
    "studentId": "CSE401D",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Mahmud Ahmad",
    "motherName": "Fatima Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 750000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Faisal_Ahmad_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 402,
    "seat": "A",
    "name": "Taher Rahman",
    "department": "Law",
    "studentId": "LAW402A",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdul Rahman",
    "motherName": "Jannat Begum",
    "fatherOccupation": "Lawyer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1200000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Taher_Rahman_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 402,
    "seat": "B",
    "name": "Arman Hossain",
    "department": "BBA",
    "studentId": "BBA402B",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Ehsan Hossain",
    "motherName": "Rukhsana Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 500000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Arman_Hossain_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 402,
    "seat": "C",
    "name": "Tariq Jamil",
    "department": "CSE",
    "studentId": "CSE402C",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Mohammad Jamil",
    "motherName": "Asma Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 650000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tariq_Jamil_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 402,
    "seat": "D",
    "name": "Saad Mirza",
    "department": "EEE",
    "studentId": "EEE402D",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Riaz Mirza",
    "motherName": "Salma Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Saad_Mirza_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 403,
    "seat": "A",
    "name": "Abdur Rahman",
    "department": "Law",
    "studentId": "LAW403A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Abdul Rahman",
    "motherName": "Mariam Begum",
    "fatherOccupation": "Lawyer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 950000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Abdur_Rahman_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 403,
    "seat": "B",
    "name": "Rahat Hossain",
    "department": "CSE",
    "studentId": "CSE403B",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Faisal Hossain",
    "motherName": "Nashit Begum",
    "fatherOccupation": "Doctor",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1400000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rahat_Hossain_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 403,
    "seat": "C",
    "name": "Imran Ali",
    "department": "BBA",
    "studentId": "BBA403C",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Salim Ali",
    "motherName": "Fatima Ali",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Imran_Ali_Signature.png",
    "timeRemaining": "11 months"
  },
  {
    "roomNumber": 403,
    "seat": "D",
    "name": "Khaled Hasan",
    "department": "EEE",
    "studentId": "EEE403D",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Naim Hasan",
    "motherName": "Rahela Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 900000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Khaled_Hasan_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 404,
    "seat": "A",
    "name": "Shahriar Ahmed",
    "department": "CSE",
    "studentId": "CSE404A",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Ahsan Ahmed",
    "motherName": "Nur Jahan",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 950000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Shahriar_Ahmed_Signature.png",
    "timeRemaining": "9 months"
  },
  {
    "roomNumber": 404,
    "seat": "B",
    "name": "Rohit Chowdhury",
    "department": "BBA",
    "studentId": "BBA404B",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Shamsul Chowdhury",
    "motherName": "Nasrin Chowdhury",
    "fatherOccupation": "Lawyer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1100000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rohit_Chowdhury_Signature.png",
    "timeRemaining": "7 months"
  },
  {
    "roomNumber": 404,
    "seat": "C",
    "name": "Imran Hossain",
    "department": "EEE",
    "studentId": "EEE404C",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Javed Hossain",
    "motherName": "Sharmin Hossain",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 800000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Imran_Hossain_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 404,
    "seat": "D",
    "name": "Saif Rahman",
    "department": "CSE",
    "studentId": "CSE404D",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Asad Rahman",
    "motherName": "Momena Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 650000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Saif_Rahman_Signature.png",
    "timeRemaining": "10 months"
  },
  {
    "roomNumber": 405,
    "seat": "A",
    "name": "Faisal Alam",
    "department": "BBA",
    "studentId": "BBA405A",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Mohammad Alam",
    "motherName": "Sumaiya Alam",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 750000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Faisal_Alam_Signature.png",
    "timeRemaining": "12 months"
  },
  {
    "roomNumber": 405,
    "seat": "B",
    "name": "Samiul Islam",
    "department": "CSE",
    "studentId": "CSE405B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Abdur Rahman",
    "motherName": "Nabila Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 650000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Samiul_Islam_Signature.png",
    "timeRemaining": "8 months"
  },
  {
    "roomNumber": 405,
    "seat": "C",
    "name": "Riyad Khan",
    "department": "EEE",
    "studentId": "EEE405C",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Rauf Khan",
    "motherName": "Sharmin Khan",
    "fatherOccupation": "Doctor",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 950000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Riyad_Khan_Signature.png",
    "timeRemaining": "11 months"
  },
  {
    "roomNumber": 405,
    "seat": "D",
    "name": "Tariq Ahsan",
    "department": "Law",
    "studentId": "LAW405D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Rafiq Ahsan",
    "motherName": "Mahbuba Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1100000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tariq_Ahsan_Signature.png",
    "timeRemaining": "6 months"
  },

  {
    "roomNumber": 501,
    "seat": "A",
    "name": "Fahim Islam",
    "department": "ICT",
    "studentId": "ICT501A",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Abdul Islam",
    "motherName": "Rubina Islam",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Fahim_Islam_Signature.png",
    "timeRemaining": "2 years"
  },
  {
    "roomNumber": 501,
    "seat": "B",
    "name": "Rashedul Alam",
    "department": "CSS",
    "studentId": "CSS501B",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Rashid Alam",
    "motherName": "Nashimah Alam",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 2200000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rashedul_Alam_Signature.png",
    "timeRemaining": "2 years"
  },
  {
    "roomNumber": 501,
    "seat": "C",
    "name": "Rifat Mollah",
    "department": "ME",
    "studentId": "ME501C",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Monir Mollah",
    "motherName": "Khaleda Begum",
    "fatherOccupation": "Farmer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 800000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rifat_Mollah_Signature.png",
    "timeRemaining": "2 years"
  },
  {
    "roomNumber": 501,
    "seat": "D",
    "name": "Hassan Ali",
    "department": "Math",
    "studentId": "Math501D",
    "season": "2022-23",
    "yearOrSemester": "1st Year",
    "fatherName": "Akram Ali",
    "motherName": "Shamim Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Hassan_Ali_Signature.png",
    "timeRemaining": "2 years"
  },
  {
    "roomNumber": 502,
    "seat": "A",
    "name": "Nashit Islam",
    "department": "Statics",
    "studentId": "Statics502A",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Kamrul Islam",
    "motherName": "Sultana Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Teacher",
    "relativeToTangail": "Yes",
    "annualIncome": 1700000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Nashit_Islam_Signature.png",
    "timeRemaining": "1 year"
  },
  {
    "roomNumber": 502,
    "seat": "B",
    "name": "Ramon Kadir",
    "department": "BBA",
    "studentId": "BBA502B",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Aminur Kadir",
    "motherName": "Razia Kadir",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1900000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Ramon_Kadir_Signature.png",
    "timeRemaining": "1 year"
  },
  {
    "roomNumber": 502,
    "seat": "C",
    "name": "Tanvir Ahmed",
    "department": "Pharmacy",
    "studentId": "Pharmacy502C",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Jasim Ahmed",
    "motherName": "Shamima Ahmed",
    "fatherOccupation": "Doctor",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 2100000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tanvir_Ahmed_Signature.png",
    "timeRemaining": "1 year"
  },
  {
    "roomNumber": 502,
    "seat": "D",
    "name": "Asif Reza",
    "department": "BGE",
    "studentId": "BGE502D",
    "season": "2022-23",
    "yearOrSemester": "2nd Year",
    "fatherName": "Farid Reza",
    "motherName": "Parveen Reza",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Teacher",
    "relativeToTangail": "Yes",
    "annualIncome": 2200000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Asif_Reza_Signature.png",
    "timeRemaining": "1 year"
  },
  {
    "roomNumber": 503,
    "seat": "A",
    "name": "Shihab Hossain",
    "department": "BMB",
    "studentId": "BMB503A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Mokbul Hossain",
    "motherName": "Khaleda Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1600000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Shihab_Hossain_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 503,
    "seat": "B",
    "name": "Nadim Islam",
    "department": "ICT",
    "studentId": "ICT503B",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Sayed Islam",
    "motherName": "Rukhsana Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1300000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Nadim_Islam_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 503,
    "seat": "C",
    "name": "Tariq Ahsan",
    "department": "CSS",
    "studentId": "CSS503C",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Rafiq Ahsan",
    "motherName": "Mahbuba Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1100000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tariq_Ahsan_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 503,
    "seat": "D",
    "name": "Rizwan Hossain",
    "department": "Math",
    "studentId": "Math503D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Samsul Hossain",
    "motherName": "Sharmin Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 2000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rizwan_Hossain_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 504,
    "seat": "A",
    "name": "Zahidul Islam",
    "department": "ICT",
    "studentId": "ICT504A",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Jahidul Islam",
    "motherName": "Shamima Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1500000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Zahidul_Islam_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 504,
    "seat": "B",
    "name": "Rashedul Hasan",
    "department": "CSS",
    "studentId": "CSS504B",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Sayed Hasan",
    "motherName": "Rukhsana Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 1800000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Rashedul_Hasan_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 504,
    "seat": "C",
    "name": "Tanvir Rahman",
    "department": "ME",
    "studentId": "ME504C",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Md. Rahman",
    "motherName": "Shahida Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 1900000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Tanvir_Rahman_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 504,
    "seat": "D",
    "name": "Aminul Islam",
    "department": "Math",
    "studentId": "Math504D",
    "season": "2022-23",
    "yearOrSemester": "3rd Year",
    "fatherName": "Ibrahim Islam",
    "motherName": "Sharmin Begum",
    "fatherOccupation": "Engineer",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 2000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Aminul_Islam_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 505,
    "seat": "A",
    "name": "Sohail Ahmed",
    "department": "Statics",
    "studentId": "Statics505A",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Ahmed Hossain",
    "motherName": "Sultana Begum",
    "fatherOccupation": "Teacher",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 2200000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Sohail_Ahmed_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 505,
    "seat": "B",
    "name": "Sabbir Rahman",
    "department": "BBA",
    "studentId": "BBA505B",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Mohammad Rahman",
    "motherName": "Parveen Rahman",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 2500000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Sabbir_Rahman_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 505,
    "seat": "C",
    "name": "Mizanur Rahman",
    "department": "Pharmacy",
    "studentId": "Pharmacy505C",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Nasir Rahman",
    "motherName": "Razia Rahman",
    "fatherOccupation": "Doctor",
    "motherOccupation": "Housewife",
    "relativeToTangail": "Yes",
    "annualIncome": 3000000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Mizanur_Rahman_Signature.png",
    "timeRemaining": "6 months"
  },
  {
    "roomNumber": 505,
    "seat": "D",
    "name": "Bashir Uddin",
    "department": "BGE",
    "studentId": "BGE505D",
    "season": "2022-23",
    "yearOrSemester": "4th Year",
    "fatherName": "Ismail Uddin",
    "motherName": "Anwara Begum",
    "fatherOccupation": "Businessman",
    "motherOccupation": "Housewife",
    "relativeToTangail": "No",
    "annualIncome": 2300000,
    "mobileNumber": "015XXXXXXXX",
    "signature": "Bashir_Uddin_Signature.png",
    "timeRemaining": "6 months"
  }









]
